const subtitles={
    subtitles:[
        [2.76,"Why do I do this?"],
        [5.55,"Pick you up and put you down and put you through this"],
        [6,""],
        [11.55,"Started off as a good thing, a sure thing, you held back but I know"],
        [13.42,"In the moment our lips touched"],
        [16.75,"The rush sent us straight to the moon"],
        [19.12,"I should've known that we'd be coming down"],
        [23,"Right to the bottom where we are now, hmm"],
        [28.8,"Started off as a good thing, a sure thing, what the hell did I do? Yeah"],
        [31.5,"Every time I think I Love Somebody"],
        [35,"Always find a way to throw it all away"],
        [37.5,"I don't ever wanna hurt nobody"],
        [40.2,"I don't wanna be the one to say"],
        [43.5,"That we gotta have a conversation"],
        [46.3,"I don't wanna watch the tears roll down your face"],
        [49,"Know, I hurt you, and I, I'm sorry"],
        [51.8,"All I wanted was to Love Somebody"],
        [54.2,"Why do I do this?"],
        [57.4,"Pick you up and put you down and put you through this"],
        [63.1,"Started off as a good thing, a sure thing, you held back but I know"],
        [65.1,"In the moment our lips touched"],
        [68.1,"The rush sent us straight to the moon"],
        [70.8,"I should've known that we'd be coming down"],
        [74.5,"Right to the bottom where we are now, hmm"],
        [80.2,"Started off as a good thing, a sure thing, what the hell did I do? Yeah"],
        [83.4,"Every time I think I Love Somebody"],
        [86.2,"Always find a way to throw it all away"],
        [89,"I don't ever wanna hurt nobody"],
        [91.5,"I don't wanna be the one to say"],
        [94.8,"That we gotta have a conversation"],
        [97.8,"I don't wanna watch the tears roll down your face"],
        [100.6,"Know, I hurt you, and I, I'm sorry"],
        [103.18,"All I wanted was to Love Somebody"],
        [105.6,"Why do I do this?"],
        [108.45,"Pick you up and put you down and put you through this"],
        [111.4,"Oh, why do I do this?"],
        [114.08,"Pick you up and put you down and put you through this"],
        [116.87,"Oh, why do I do this? (Every time I think I Love Somebody)"],
        [119.95,"Pick you up and put you down and put you through this"],
        [122.88,"Oh, why do I do this? (I don't ever wanna hurt nobody)"],
        [126.14,"Pick you up and put you down and put you through this"],
        [129.25,"That we gotta have a conversation"],
        [132.12,"I don't wanna watch the tears roll down your face"],
        [134.6,"Know, I hurt you, and I, I'm sorry"],
        [137.93,"All I wanted was to Love Somebody"],
        [138.9,""]
    ],
};
